.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH OSMO-TRX 1 "Februray 07, 2015"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
osmo-trx \- SDR transceiver that implements Layer 1 of a GSM BTS
.SH SYNOPSIS
.B osmo-trx
.SH DESCRIPTION
This manual page documents briefly the
.B osmo-trx
command.
.PP
\fBosmo-trx\fP is a software-defined radio transceiver that implements the Layer 1
physical layer of a BTS comprising the following 3GPP specifications:
.
.PP
.br
TS 05.01 "Physical layer on the radio path"
.br
TS 05.02 "Multiplexing and Multiple Access on the Radio Path"
.br
TS 05.04 "Modulation"
.br
TS 05.10 "Radio subsystem synchronization"
.PP
In this context, BTS is "Base transceiver station". It's the stations that
connect mobile phones to the mobile network.
.PP
3GPP is the "3rd Generation Partnership Project" which is the collaboration
between different telecommunication associations for developing new
generations of mobile phone networks. (post-2G/GSM)

.\".SH OPTIONS
.br
.SH AUTHOR
This manual page was written by Ruben Undheim <ruben.undheim@gmail.com>,
for the Debian project (and may be used by others).
